[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY = "0x4AAAAAADGfqsWqTSik59uD"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dp9lv8q5e"

[[plugins]]
  package = "@netlify/plugin-nextjs"
